### ISSUE TITLE
bug: broken website stenciljs.com on mobile browser

### ISSUE THREAD

**Issue by DavidWiesner** [ionic-team/stencil-site#190]
efore a month I added the stenciljs.com site as PWA-app to my homescreen.

After opening the site today I only can see the header of the page without any content. Also the menu has no items.

![screenshot_20180614-153440](https://user-images.githubusercontent.com/243115/41612454-486a8ec2-73f3-11e8-972e-c57178923079.png)

When opening the website on my Desktop browser I can see the frontpage and also the menu has items. And all looks fine but I got an error in the console after clearing the cache and unregister the service worker.

```
Uncaught (in promise) r: cache-put-with-no-response :: [{"url":"/assets/img/ionic-os-logo.png"}]
    at Object.<anonymous> (https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-core.prod.js:1:2488)
    at Generator.next (<anonymous>)
    at n (https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-core.prod.js:1:167)
    at https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-core.prod.js:1:306
    at new Promise (<anonymous>)
    at Object.<anonymous> (https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-core.prod.js:1:104)
    at Object.N [as put] (https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-core.prod.js:1:2776)
    at https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-precaching.prod.js:1:2927
    at Generator.next (<anonymous>)
    at n (https://storage.googleapis.com/workbox-cdn/releases/3.2.0/workbox-core.prod.js:1:167)
Service Worker termination by a timeout timer was canceled because DevTools is attached.
```

Maybe this is related to the broken page on mobile browser.
--
Android 8.1
Chrome 67.0.3396.87

**Comment by jgw96** [comment]
Hey! This is a known issue that is service worker related and we are currently working on a fix for it (im testing the fix as we speak). Ill update this issue once i have updated the site with the fix. Thanks!

**Comment by jgw96** [comment]
Alright, this issue has been fixed. The fix was implemented in Stencil and i just pushed a new version of the site built with the latest version of Stencil.
